stages:
    - build
    - package
    - deploy

.production:
    only:
        - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i
    environment:
        name: production

include:
    - local: .gitlab/build/linux.gitlab-ci.yml
    - local: .gitlab/build/windows.gitlab-ci.yml
    - local: .gitlab/build/macos.gitlab-ci.yml
    - local: .gitlab/deploy.gitlab-ci.yml
