stages:
    - dependencies
    - build
    - package
    - deploy

.production:
    only:
        - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i
    environment:
        name: production

tivoli scripts:
    stage: dependencies
    image: node:lts
    # extends: .production
    script:
        - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@git.tivolicloud.com/tivolicloud-private/tivoli-scripts
        - cd tivoli-scripts
        - yarn install
        - yarn build
        - mv dist/* ../scripts

    artifacts:
        expire_in: 1 days
        paths:
            - scripts/tivoli/
            - scripts/tivoli.js

include:
    - local: .gitlab/build/linux.gitlab-ci.yml
    - local: .gitlab/build/windows.gitlab-ci.yml
    - local: .gitlab/build/macos.gitlab-ci.yml
    - local: .gitlab/deploy.gitlab-ci.yml
