stages:
    - dependencies
    - build
    - package
    - deploy

.production-trigger:
    only:
        - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i

.production:
    extends: .production-trigger
    environment:
        name: production

# TODO: should probably move pipeline to here
tivoli scripts:
    stage: dependencies
    image: python:latest
    extends: .production
    script:
        - python .gitlab/tivoli-scripts.py
    artifacts:
        expire_in: 1 days
        paths:
            - scripts/tivoli/
            - scripts/tivoli.js

include:
    - local: .gitlab/build/linux.gitlab-ci.yml
    - local: .gitlab/build/windows.gitlab-ci.yml
    - local: .gitlab/build/macos.gitlab-ci.yml
    - local: .gitlab/deploy.gitlab-ci.yml
