name: Linux build images
on:
    push:
        paths:
            - docker/linux.Dockerfile
            - cmake/ports/**
            - hifi_qt.py
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch:
                    - amd64
                    - arm64
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Set up QEMU
              if: matrix.arch != 'amd64'
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: arm64

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@master

            - name: Build and push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  builder: ${{ steps.buildx.outputs.name }}
                  context: docker
                  file: docker/linux.Dockerfile
                  platforms: linux/${{ matrix.arch }}
                  tags: tivolicloud/build:linux-${{ matrix.arch }}
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  push: true
