# this file deploy to production
# please be careful not to run this by accident!

.deploy:
    extends: .production
    when: manual

pages:
    stage: deploy
    image: node:latest

    extends: .deploy

    script:
        - cd tools/jsdoc
        - npm install
        - npm run build
        - mv out ../../public

    artifacts:
        paths:
            - public

upload server:
    stage: deploy
    image: docker:latest

    extends: .deploy

    dependencies:
        - server linux

    variables:
        DOCKER_TLS_CERTDIR: ""

    services:
        - docker:dind

    script:
        - docker system info
        - docker image ls
        - cd docker

        # prepare server image
        - cd server
        - mkdir -p dist

        - cp ../../build/domain-server/domain-server dist/domain-server
        - cp ../../build/assignment-client/assignment-client dist/assignment-client
        - cp ../../build/tools/oven/oven dist/oven
        - cp -r ../../build/domain-server/resources dist/resources
        - cp -r ../../build/domain-server/lib dist/lib
        - cp ecosystem.config.js dist

        # build server image
        - docker build
          -t tivolicloud/server:$CI_COMMIT_TAG
          -t tivolicloud/server:latest
          -t registry.tivolicloud.com/tivolicloud/interface/server:$CI_COMMIT_TAG
          -t registry.tivolicloud.com/tivolicloud/interface/server:latest
          .
        - docker image ls
        - cd ..

        # prepare ice image
        - cd ice
        - mkdir -p dist

        - cp ../../build/ice-server/ice-server dist/ice-server
        - cp -r ../../build/ice-server/lib dist/lib

        # build ice image
        - docker build
          -t registry.tivolicloud.com/tivolicloud/interface/ice:latest
          .
        - docker image ls
        - cd ..

        # publish server to docker hub
        - docker login --username makitsune --password $DOCKER_HUB_ACCESS_TOKEN
        - docker push tivolicloud/server:$CI_COMMIT_TAG
        - docker push tivolicloud/server:latest

        # publish server and ice to our registry
        - docker login registry.tivolicloud.com --username gitlab-ci-token --password $CI_JOB_TOKEN
        - docker push registry.tivolicloud.com/tivolicloud/interface/server:$CI_COMMIT_TAG
        - docker push registry.tivolicloud.com/tivolicloud/interface/server:latest
        - docker push registry.tivolicloud.com/tivolicloud/interface/ice:latest

upload interface:
    stage: deploy
    image: node:lts

    extends: .deploy

    dependencies:
        - launcher windows
        - launcher macos

    script:
        - cd .gitlab
        - yarn install
        - ls ../launcher/dist
        # needs DO_KEY_ID, DO_SECRET_KEY
        - node deploy.js ../launcher/dist
