finalize server:
    stage: finalize
    image: docker:latest

    extends: .deploy

    variables:
        DOCKER_TLS_CERTDIR: ""

    dependencies:
        - upload server
        - upload server arm64

    services:
        - name: docker:dind
          command: ["--experimental"]

    script:
        - mkdir -p ~/.docker
        - 'echo ''{"experimental": "enabled"}'' > ~/.docker/config.json'

        - docker system info
        - docker image ls

        # create manifests for our registry and upload

        - docker manifest create $CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG
          --amend $CI_REGISTRY_IMAGE/server:amd64-$CI_COMMIT_TAG
          --amend $CI_REGISTRY_IMAGE/server:arm64-$CI_COMMIT_TAG
        - docker manifest create $CI_REGISTRY_IMAGE/server:latest
          --amend $CI_REGISTRY_IMAGE/server:amd64-$CI_COMMIT_TAG
          --amend $CI_REGISTRY_IMAGE/server:arm64-$CI_COMMIT_TAG

        - docker login registry.tivolicloud.com --username gitlab-ci-token --password $CI_JOB_TOKEN
        - docker manifest push $CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG
        - docker manifest push $CI_REGISTRY_IMAGE/server:latest

        # upload and create manifests for docker hub

        - docker pull $CI_REGISTRY_IMAGE/server:amd64-$CI_COMMIT_TAG
        - docker pull $CI_REGISTRY_IMAGE/server:arm64-$CI_COMMIT_TAG
        - docker tag $CI_REGISTRY_IMAGE/server:amd64-$CI_COMMIT_TAG tivolicloud/server:amd64-$CI_COMMIT_TAG
        - docker tag $CI_REGISTRY_IMAGE/server:arm64-$CI_COMMIT_TAG tivolicloud/server:arm64-$CI_COMMIT_TAG
        - docker push tivolicloud/server:amd64-$CI_COMMIT_TAG
        - docker push tivolicloud/server:arm64-$CI_COMMIT_TAG

        - docker manifest create tivolicloud/server:$CI_COMMIT_TAG
          --amend tivolicloud/server:amd64-$CI_COMMIT_TAG
          --amend tivolicloud/server:arm64-$CI_COMMIT_TAG
        - docker manifest create tivolicloud/server:latest
          --amend tivolicloud/server:amd64-$CI_COMMIT_TAG
          --amend tivolicloud/server:arm64-$CI_COMMIT_TAG

        - docker login --username makitsune --password $DOCKER_HUB_ACCESS_TOKEN
        - docker manifest push tivolicloud/server:$CI_COMMIT_TAG
        - docker manifest push tivolicloud/server:latest

        # delete build tags

        - apk add wget
        - wget -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.16.1/reg-linux-amd64
        - chmod +x /usr/bin/reg

        - reg rm -u $CI_REGISTRY_IMAGE/server:amd64-$CI_COMMIT_TAG
        - reg rm -u $CI_REGISTRY_IMAGE/server:arm64-$CI_COMMIT_TAG

        - reg rm -u tivolicloud/server:amd64-$CI_COMMIT_TAG
        - reg rm -u tivolicloud/server:arm64-$CI_COMMIT_TAG
