finalize server:
    stage: finalize
    image: docker:latest

    # extends: .deploy

    variables:
        DOCKER_TLS_CERTDIR: ""

    # dependencies:
    #     - upload server
    #     - upload server arm64

    services:
        - name: docker:dind
          command: ["--experimental"]

    script:
        - mkdir -p ~/.docker
        - 'echo ''{"experimental": "enabled"}'' > ~/.docker/config.json'

        - docker system info
        - docker image ls

        # login

        - docker login registry.tivolicloud.com -u gitlab-ci-token -p $CI_JOB_TOKEN
        - docker login -u makitsune -p $DOCKER_HUB_ACCESS_TOKEN

        # create manifests for our registry and upload

        - docker manifest create $CI_REGISTRY_IMAGE/server:0.10.4
          --amend $CI_REGISTRY_IMAGE/server:amd64-0.10.4
          --amend $CI_REGISTRY_IMAGE/server:arm64-0.10.4
        - docker manifest create $CI_REGISTRY_IMAGE/server:latest
          --amend $CI_REGISTRY_IMAGE/server:amd64-0.10.4
          --amend $CI_REGISTRY_IMAGE/server:arm64-0.10.4

        - docker manifest push $CI_REGISTRY_IMAGE/server:0.10.4
        - docker manifest push $CI_REGISTRY_IMAGE/server:latest

        # upload and create manifests for docker hub

        - docker pull $CI_REGISTRY_IMAGE/server:amd64-0.10.4
        - docker pull $CI_REGISTRY_IMAGE/server:arm64-0.10.4
        - docker tag $CI_REGISTRY_IMAGE/server:amd64-0.10.4 tivolicloud/server:amd64-0.10.4
        - docker tag $CI_REGISTRY_IMAGE/server:arm64-0.10.4 tivolicloud/server:arm64-0.10.4
        - docker push tivolicloud/server:amd64-0.10.4
        - docker push tivolicloud/server:arm64-0.10.4

        - docker manifest create tivolicloud/server:0.10.4
          --amend tivolicloud/server:amd64-0.10.4
          --amend tivolicloud/server:arm64-0.10.4
        - docker manifest create tivolicloud/server:latest
          --amend tivolicloud/server:amd64-0.10.4
          --amend tivolicloud/server:arm64-0.10.4

        - docker manifest push tivolicloud/server:0.10.4
        - docker manifest push tivolicloud/server:latest

        # delete build tags

        - apk add wget
        - wget -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.16.1/reg-linux-amd64
        - chmod +x /usr/bin/reg

        - reg rm $CI_REGISTRY_IMAGE/server:amd64-0.10.4
        - reg rm $CI_REGISTRY_IMAGE/server:arm64-0.10.4

        - reg rm tivolicloud/server:amd64-0.10.4
        - reg rm tivolicloud/server:arm64-0.10.4
